server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Gérer le routage des Single Page Applications (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache pour les assets statiques
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Compression Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
